package:
  name: pytest-benchmark
  version: "3.0.0"

source:
  fn: pytest-benchmark-3.0.0.zip
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-3.0.0.zip
  md5: f8ab8e438f039366e3765168ad831b4c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-benchmark = pytest-benchmark:main
    #
    # Would create an entry point called pytest-benchmark that calls pytest-benchmark.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.6

  run:
    - python
    - setuptools
    - pytest >=2.6

test:
  # Python imports
  imports:
    - pytest_benchmark

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD License
  summary: 'A ``py.test`` fixture for benchmarking code.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
